runs:
  using: "composite"
  steps:
    - name: Prisma Cloud image scan
      id: scan
      uses: PaloAltoNetworks/prisma-cloud-scan@v1
      with:
        pcc_console_url: ${{ inputs.PCC_CONSOLE_URL }}
        pcc_user: ${{ inputs.PCC_USER }}
        pcc_pass: ${{ inputs.PCC_PASS }}
        image_name: ${{ inputs.IMAGE_NAME }}
